version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: "/apps/api"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "/apps/bot"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "/apps/admin"
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
